<?php
/** @var \HoloScope\ViewModel\PageViewModel $view */
require_once dirname(__DIR__) . '/helpers.php';
$entity = $view->data['entity'];
?>
<article class="member-detail discovery-detail">
<header class="detail-header"><p class="eyebrow">GAME</p><h1><?= e($entity['name']) ?></h1><p class="lead"><?= e($entity['summary'] ?? '') ?></p><?php if (!empty($entity['aliases'])): ?><div class="tag-list"><?php foreach ($entity['aliases'] as $alias): ?><span><?= e($alias) ?></span><?php endforeach; ?></div><?php endif; ?><div class="metric-grid"><div><strong><?= e($entity['streamCount'] ?? 0) ?></strong><span>公開配信記事</span></div><div><strong><?= e(count($entity['topMembers'])) ?></strong><span>主な配信者</span></div><div><strong><?= e($entity['learningProfile']['evaluatedStreams'] ?? 0) ?></strong><span>学習評価済み</span></div></div><div class="actions"><a class="button" href="/holoscope<?= e($entity['streamSearchUrl']) ?>">このゲームの配信を検索</a><?php if (!empty($entity['officialUrl'])): ?><a class="button secondary" href="<?= e($entity['officialUrl']) ?>" rel="noopener noreferrer">公式サイト</a><?php endif; ?></div></header>
<section><div class="section-heading"><h2>最新の配信</h2><a href="/holoscope<?= e($entity['streamSearchUrl']) ?>">すべて見る</a></div><div class="stream-card-grid"><?php foreach ($entity['latestStreams'] as $card): require dirname(__DIR__) . '/components/stream-card.php'; endforeach; ?></div></section>
<section><div class="two-column"><div><h2>主な配信者</h2><ol class="rank-list"><?php foreach ($entity['topMembers'] as $member): ?><li><a href="/holoscope/members/<?= e($member['slug']) ?>/"><?= e($member['displayName']) ?></a><strong><?= e($member['streamCount']) ?>件</strong></li><?php endforeach; ?></ol></div><div><h2>配信分類</h2><ol class="rank-list"><?php foreach ($entity['streamTypes'] as $item): ?><li><span><?= e($item['label']) ?></span><strong><?= e($item['count']) ?>件</strong></li><?php endforeach; ?></ol></div></div></section>
<section><h2>関連する企画・シリーズ</h2><div class="two-column"><div><h3>企画</h3><ol class="rank-list"><?php foreach ($entity['relatedEvents'] as $item): ?><li><a href="/holoscope/events/<?= e($item['slug']) ?>/"><?= e($item['name']) ?></a><strong><?= e($item['streamCount']) ?>件</strong></li><?php endforeach; ?></ol></div><div><h3>シリーズ</h3><ol class="rank-list"><?php foreach ($entity['relatedSeries'] as $item): ?><li><a href="/holoscope/series/<?= e($item['slug']) ?>/"><?= e($item['name']) ?></a><strong><?= e($item['streamCount']) ?>件</strong></li><?php endforeach; ?></ol></div></div></section>
<section><h2>英語学習プロフィール</h2><?php $learning = $entity['learningProfile']; require dirname(__DIR__) . '/components/learning-summary.php'; ?></section>
<section><h2>関連特集</h2><?php $articles = $entity['relatedArticles']; require dirname(__DIR__) . '/components/related-articles.php'; ?></section>
</article>
