<?php
/** @var \HoloScope\ViewModel\PageViewModel $view */
require_once dirname(__DIR__) . '/helpers.php';
$entity = $view->data['entity'];
?>
<article class="member-detail discovery-detail">
<header class="detail-header"><p class="eyebrow">SERIES</p><h1><?= e($entity['name']) ?></h1><p class="lead"><?= e($entity['summary'] ?? '') ?></p><div class="series-status-grid"><div><span>目標</span><strong><?= e($entity['goal'] ?? '未設定') ?></strong></div><div><span>現在の進捗</span><strong><?= e($entity['progress'] ?? '未設定') ?></strong></div></div><div class="metric-grid"><div><strong><?= e($entity['episodeCount'] ?? 0) ?></strong><span>公開エピソード</span></div><div><strong><?= e(count($entity['members'])) ?></strong><span>登場メンバー</span></div><div><strong><?= e($entity['learningProfile']['evaluatedStreams'] ?? 0) ?></strong><span>学習評価済み</span></div></div><div class="actions"><a class="button" href="/holoscope<?= e($entity['streamSearchUrl']) ?>">このシリーズの配信を検索</a></div></header>
<section><div class="section-heading"><h2>エピソード</h2><p>編集原本の表示順に掲載</p></div><ol class="episode-list"><?php foreach ($entity['episodes'] as $episode): $card = $episode['stream']; ?><li><div class="episode-number"><span><?= $episode['episodeNumber'] !== null ? 'EP.' . e($episode['episodeNumber']) : 'EXTRA' ?></span><small><?= e($episode['episodeType']) ?></small></div><div class="episode-content"><?php require dirname(__DIR__) . '/components/stream-card.php'; ?></div></li><?php endforeach; ?></ol></section>
<section><div class="two-column"><div><h2>登場メンバー</h2><ol class="rank-list"><?php foreach ($entity['members'] as $member): ?><li><a href="/holoscope/members/<?= e($member['slug']) ?>/"><?= e($member['displayName']) ?></a><strong><?= e($member['streamCount']) ?>話</strong></li><?php endforeach; ?></ol></div><div><h2>関連ゲーム</h2><ol class="rank-list"><?php foreach ($entity['games'] as $game): ?><li><a href="/holoscope/games/<?= e($game['slug']) ?>/"><?= e($game['name']) ?></a><strong><?= e($game['streamCount']) ?>話</strong></li><?php endforeach; ?></ol></div></div><?php if ($entity['events'] !== []): ?><h3>関連企画</h3><div class="tag-list"><?php foreach ($entity['events'] as $event): ?><a href="/holoscope/events/<?= e($event['slug']) ?>/"><?= e($event['name']) ?>（<?= e($event['streamCount']) ?>）</a><?php endforeach; ?></div><?php endif; ?></section>
<section><h2>英語学習プロフィール</h2><?php $learning = $entity['learningProfile']; require dirname(__DIR__) . '/components/learning-summary.php'; ?></section>
<section><h2>関連特集</h2><?php $articles = $entity['relatedArticles']; require dirname(__DIR__) . '/components/related-articles.php'; ?></section>
</article>
