const $=s=>document.querySelector(s);document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.experiment").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")});
const fruit=[{x:120,y:72,c:0},{x:135,y:68,c:0},{x:150,y:65,c:0},{x:165,y:61,c:0},{x:180,y:58,c:0},{x:190,y:38,c:1},{x:210,y:34,c:1},{x:225,y:31,c:1},{x:240,y:27,c:1},{x:255,y:24,c:1}];
const study=[{x:1,y:38},{x:2,y:45},{x:3,y:51},{x:4,y:57},{x:5,y:64},{x:6,y:70},{x:7,y:76},{x:8,y:83},{x:9,y:88},{x:10,y:94}];
function line(data){let n=data.length,sx=0,sy=0,sxy=0,sxx=0;data.forEach(p=>{sx+=p.x;sy+=p.y;sxy+=p.x*p.y;sxx+=p.x*p.x});let m=(n*sxy-sx*sy)/(n*sxx-sx*sx),b=(sy-m*sx)/n;return{m,b}}
function axes(c,xmin,xmax,ymin,ymax){let g=c.getContext("2d"),W=c.width,H=c.height,p=45;g.clearRect(0,0,W,H);g.strokeStyle="#b8ad91";g.beginPath();g.moveTo(p,15);g.lineTo(p,H-p);g.lineTo(W-15,H-p);g.stroke();return{x:v=>p+(v-xmin)/(xmax-xmin)*(W-p-20),y:v=>H-p-(v-ymin)/(ymax-ymin)*(H-p-20),g}}
function dot(a,x,y,color,r=6){a.g.fillStyle=color;a.g.beginPath();a.g.arc(a.x(x),a.y(y),r,0,Math.PI*2);a.g.fill()}
function drawClass(test){let c=$("#classCanvas"),a=axes(c,100,270,15,80);fruit.forEach(p=>dot(a,p.x,p.y,p.c?"#214e79":"#b43a2b"));a.g.strokeStyle="#92743e";a.g.setLineDash([7,5]);a.g.beginPath();a.g.moveTo(a.x(100),a.y(18));a.g.lineTo(a.x(270),a.y(70));a.g.stroke();a.g.setLineDash([]);if(test)dot(a,test.x,test.y,"#17130d",8)}
drawClass();$("#classCanvas").onclick=e=>{let c=e.currentTarget,r=c.getBoundingClientRect(),px=(e.clientX-r.left)*c.width/r.width,py=(e.clientY-r.top)*c.height/r.height,p=45,x=100+(px-p)/(c.width-p-20)*170,y=15+(c.height-p-py)/(c.height-p-20)*65;if(x<100||x>270||y<15||y>80)return;let boundary=18+(x-100)*52/170,kind=y>boundary?"りんご側":"みかん側";drawClass({x,y});$("#classResult").textContent=`重さ 約${x.toFixed(0)}g・色値 ${y.toFixed(0)} → ${kind} と分類`};
function drawReg(canvas,data,mark){let a=axes(canvas,0,11,30,100),l=line(data);data.forEach(p=>dot(a,p.x,p.y,"#214e79",5));a.g.strokeStyle="#b43a2b";a.g.lineWidth=2;a.g.beginPath();a.g.moveTo(a.x(0),a.y(l.b));a.g.lineTo(a.x(11),a.y(l.m*11+l.b));a.g.stroke();if(mark!=null)dot(a,mark,l.m*mark+l.b,"#17130d",7);return l}
function updateReg(){let h=+$("#hours").value,l=drawReg($("#regCanvas"),study,h),score=l.m*h+l.b;$("#hoursLabel").textContent=h.toFixed(1)+"時間";$("#scoreResult").textContent=`予測点: 約${score.toFixed(1)}点。データ全体から傾向を表す直線を計算しています。`}
$("#hours").oninput=updateReg;updateReg();
function updateScarce(){let n=+$("#count").value,d=study.slice(0,n),l=drawReg($("#scarceCanvas"),d,8),pred=l.m*8+l.b,full=line(study),base=full.m*8+full.b;$("#countLabel").textContent=n+"件";$("#scarceResult").textContent=`8時間の予測: ${pred.toFixed(1)}点。全10件での予測との差は ${Math.abs(pred-base).toFixed(1)}点。`}
$("#count").oninput=updateScarce;updateScarce();